# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_to_text_grpc_pb2 as audio__to__text__grpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_to_text_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioToTextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Align = channel.stream_unary(
                '/svg_tools.audio_to_text.v1.AudioToText/Align',
                request_serializer=audio__to__text__grpc__pb2.AlignChunk.SerializeToString,
                response_deserializer=audio__to__text__grpc__pb2.AlignResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/svg_tools.audio_to_text.v1.AudioToText/GetStats',
                request_serializer=audio__to__text__grpc__pb2.StatsRequest.SerializeToString,
                response_deserializer=audio__to__text__grpc__pb2.StatsResponse.FromString,
                _registered_method=True)


class AudioToTextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Align(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioToTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Align': grpc.stream_unary_rpc_method_handler(
                    servicer.Align,
                    request_deserializer=audio__to__text__grpc__pb2.AlignChunk.FromString,
                    response_serializer=audio__to__text__grpc__pb2.AlignResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=audio__to__text__grpc__pb2.StatsRequest.FromString,
                    response_serializer=audio__to__text__grpc__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'svg_tools.audio_to_text.v1.AudioToText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('svg_tools.audio_to_text.v1.AudioToText', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioToText(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Align(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/svg_tools.audio_to_text.v1.AudioToText/Align',
            audio__to__text__grpc__pb2.AlignChunk.SerializeToString,
            audio__to__text__grpc__pb2.AlignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/svg_tools.audio_to_text.v1.AudioToText/GetStats',
            audio__to__text__grpc__pb2.StatsRequest.SerializeToString,
            audio__to__text__grpc__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
