# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_to_text_grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_to_text_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61udio_to_text_grpc.proto\x12\x1asvg_tools.audio_to_text.v1\"\x8b\x01\n\tAlignInit\x12\x10\n\x08language\x18\x01 \x01(\t\x12@\n\x0bpunctuation\x18\x02 \x01(\x0e\x32+.svg_tools.audio_to_text.v1.PunctuationMode\x12\x12\n\ntranscript\x18\x03 \x01(\t\x12\x16\n\x0e\x61udio_filename\x18\x04 \x01(\t\"c\n\nAlignChunk\x12\x35\n\x04init\x18\x01 \x01(\x0b\x32%.svg_tools.audio_to_text.v1.AlignInitH\x00\x12\x13\n\twav_chunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"G\n\x0b\x41lignedWord\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rstart_seconds\x18\x02 \x01(\x01\x12\x13\n\x0b\x65nd_seconds\x18\x03 \x01(\x01\"l\n\rAlignResponse\x12\x36\n\x05words\x18\x01 \x03(\x0b\x32\'.svg_tools.audio_to_text.v1.AlignedWord\x12\x0b\n\x03srt\x18\x02 \x01(\t\x12\x16\n\x0e\x61udio_filename\x18\x03 \x01(\t*k\n\x0fPunctuationMode\x12 \n\x1cPUNCTUATION_MODE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PUNCTUATION_MODE_REMOVE\x10\x01\x12\x19\n\x15PUNCTUATION_MODE_KEEP\x10\x02\x32k\n\x0b\x41udioToText\x12\\\n\x05\x41lign\x12&.svg_tools.audio_to_text.v1.AlignChunk\x1a).svg_tools.audio_to_text.v1.AlignResponse(\x01\x42\x1f\n\x1b\x63om.svgtools.audiototext.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_to_text_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.svgtools.audiototext.v1P\001'
  _globals['_PUNCTUATIONMODE']._serialized_start=482
  _globals['_PUNCTUATIONMODE']._serialized_end=589
  _globals['_ALIGNINIT']._serialized_start=57
  _globals['_ALIGNINIT']._serialized_end=196
  _globals['_ALIGNCHUNK']._serialized_start=198
  _globals['_ALIGNCHUNK']._serialized_end=297
  _globals['_ALIGNEDWORD']._serialized_start=299
  _globals['_ALIGNEDWORD']._serialized_end=370
  _globals['_ALIGNRESPONSE']._serialized_start=372
  _globals['_ALIGNRESPONSE']._serialized_end=480
  _globals['_AUDIOTOTEXT']._serialized_start=591
  _globals['_AUDIOTOTEXT']._serialized_end=698
# @@protoc_insertion_point(module_scope)
